easy_admin:
    design:
      menu:
        - label: 'Статті'
          icon: 'newspaper-o'
          children:
            - { entity: 'Article', label: 'Статті' }
            - { entity: 'CategoryArticle', label: 'Категорі' }
            - { entity: 'Advertisement', label: 'Оголошення' }
            - { entity: 'Comment', label: 'Коментарі' }
            #- { entity: 'Article', label: 'Статті' }
            #- { entity: 'Article', label: 'Статті' }

    entities:
        Article:
          class: App\Entity\Article
          list:
            fields:
              - { property: 'title' }
              - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
              - { property: 'description' }
              - { property: 'text' }
              - { property: 'categories' }
            show:
              fields:
                - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
          form:
            fields:
              - { property: 'title' }
              - { property: 'description' }
              - { property: 'imageFile', type: 'vich_image' }
              - { property: 'body' ,type: 'fos_ckeditor' }
              - { property: 'categories' }
        CategoryArticle:
            class: App\Entity\CategoryArticle
        Advertisement:
          class: App\Entity\Advertisement
        Comment:
          class: App\Entity\Comment

      # - App\Entity\Comment
       #- App\Entity\Advertisement
       #- App\Entity\CategoryArticle
